export enum NodeREDState {
    DISABLED = 'DISABLED',
    STOPPED = 'STOPPED',
    PENDING = 'PENDING',
    RUNNING = 'RUNNING',
    STOPPING = 'STOPPING',
    RESTARTING = 'RESTARTING',
    ERROR = 'ERROR',
    UNRESPONSIVE = "UNRESPONSIVE"
}